### ISSUE TITLE
bcftools call missing from MTS

### ISSUE THREAD

**Issue by claresloggett** [galaxyproject/tools-devteam#266]
As of samtools 1.2, mpileup doesn't perform variant calling. Instead, it apparently outputs every base in the genome with a variant quality score of zero. Variant calling must now be performed by running `bcftools call` on the output of `samtools mpileup`. 

This isn't currently possible in Galaxy because only `bcftools view` is wrapped; `bcftools call` is not available. So, I think that it's currently not possible to use revision 6 of the samtools mpileup Galaxy tool for variant calling at all.

Note that previously `bcftools view` together with `samtools mpileup` *would* produce a VCF file of called variants, so the wrapped tools were enough in previous versions.

**Comment by erasche** [comment]
Hey @clareslogget. We're aware of and working on this. There's progress in my bcftools branch on the IUC repo, "call" works well. https://github.com/galaxyproject/tools-iuc/tree/bcftools1.2/tools/bcftools I'll try and handle this this week, since someone else pinged me about it too. Dave had a copy of call he was working on in this repo that we're rolling into the IUC one. Call is pretty close to done, so we may get that up on the MTS shortly, with the rest to follow.

**Comment by claresloggett** [comment]
Great news @erasche , thanks! 

Looks good, I like the idea of having one package to install for all of bcftools and it seems a necessary companion to samtools these days.

**Comment by erasche** [comment]
@claresloggett good idea! We'll add a suite that references all of samtools/bcftools as part of the PR. :) That way you can install everything in one go.
