### ISSUE TITLE
weightedaverage tool bug

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#399]
It was reported to me that the weightedaverage tool has a bug that prevents it from properly work in case the genomic features list has 0 in it (I think it wrongfully excludes the row from the avg.)

shared history: https://usegalaxy.org/u/martenson/h/weightedaverage-bug
(note the `NA` values in resulting dataset)
ping @blankenberg

**Comment by martenson** [comment]
repo is here: https://toolshed.g2.bx.psu.edu/view/devteam/weightedaverage/90611e86a998

**Comment by blankenberg** [comment]
So I took a look at this tool. It is bad in both design and implementation. 

It is using the `name` metadata column for the value, which seems kind of goofy. 

However, the cause for this error is due to a try/except around `assert float(temp[int(name_col_2)])`, which will always fail when the value is `0`/`0.0`, since zero is false. I'd guess that this was intended as a (incorrect) check on whether this field contained a floating point value (which would just raise an exception when trying to cast to float).

It also loads the entirety of the feature and interval files into memory for no good reason. And holds all of the results in memory until it is done, instead of writing them out as they are generated.

**Comment by martenson** [comment]
fixed by https://github.com/galaxyproject/tools-devteam/pull/400 and deployed on usegalaxy.org
