### ISSUE TITLE
Samtools Filter SAM or BAM fails to split on multiple regions

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#501]
**Problem**: The split fails when multiple regions/chromosomes are entered on the tool form for the option "Select regions (only used when the input is in BAM format)".

**Test history, see dataset 16** - the chroms are not recognized and only the header is output: https://usegalaxy.org/u/jen/h/test-history-bamcompare-deeptools-hisat

**Tool**: Filter SAM or BAM, output SAM or BAM files on FLAG MAPQ RG LN or by region (Galaxy Version 1.1.2)

**MTS**: https://toolshed.g2.bx.psu.edu/view/devteam/samtool_filter2/dc6ff68ea5e8

**Recent change** (and those immediately preceding it) that might be related to the problem. A change was made to split on any _whitespace_, not just a _space_: https://github.com/galaxyproject/tools-devteam/commit/11267010589803916a59e69f2420d317cee10109

**Reported by**: https://biostar.usegalaxy.org/p/26354

@scholtalbers What do you think? The test was run using Galaxy Main running release 17.09

**Comment by scholtalbers** [comment]
@jennaj , this was exactly the reason I updated the tool 🙂
So I did some more local testing - i.e. running the previous version and the one on master, which matches the latest in the toolshed. The updated version works as expected, the previous does not and throws the seen error. Since the version of the tool didn't get bumped, its a bit hard for me to determine if the tool was actually updated on usegalaxy. Can you or someone else have a look?

**Comment by jennaj** [comment]
@scholtalbers Thanks for the extra info - and for making the fix. My guess is we do not have the most current version on Main. I'll confirm that, make a ticket for a server-specific update (if that is it - sounds very much like it is!), then close this ticket out.

**Comment by jennaj** [comment]
Passed tests - dataset 16 was rerun in dataset 18 and the filter worked.

https://usegalaxy.org/u/jen/h/test-history-bamcompare-deeptools-hisat
