### ISSUE TITLE
Issues encountered with latest updates on test.galaxyproject.org.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/tools-devteam#55]
- [x] Text cannot be copied from the updated tool forms. - Aysam is aware and will fix.
- [x] Updating metadata with "auto-detect" for previously failed settings now functions.
- [x] Collect Summary Metrics' is functioning on test now.
- [ ] Picard's Sort SAM returns a green success dataset, but seems to be interpreting input data incorrectly on 'BWA for Illumina' output and the output is reject by Picard as property formatted input.
- [ ] metadata orange alert" staying persistent in the UI is cleared up
- [ ] On Test, if a dataset is an input to a "grey - waiting to run job" - you cannot modify the metadata. Since the job hasn't started yet .. and will not until the metadata issue is cleared, I expected a "blue - paused job" instead. And to be able to fix the problem through auto-detect metadata correction.
- [x] Workflow import problems = The worflow import problems are expected as some tools changed their ids. :(
- [ ] BWA for Illumina' fails if the read group settings do not use a fully capitalized "ILLUMINA". This seems tedious. Can we change it so that the info is case-insensitive?

**Comment by jennaj** [comment]
Picard's Sort SAM returns a green success dataset, but seems to be interpreting input data incorrectly on 'BWA for Illumina' output and the output is reject by Picard as property formatted input.

Related and in the same history as shared on the gist link: other Picard tools fail as well such as 'Collect Summary Metrics". Whether on a coordinated sorted input from Sort SAM or direct 'BWA for Illumnia" output.

 See https://gist.github.com/jennaj/b089cc9d6126b6a869a9

**Comment by jennaj** [comment]
Tracking note to retest metadata fix for BWA/BWA MEM tools on Test.

The issue with the "metadata orange alert" staying persistent in the UI is cleared up.

**Comment by jennaj** [comment]
Tracking note to retest issues when a simple workflow was downloaded then uploaded to test. The source workflow in on this Page: https://usegalaxy.org/u/galaxyproject/p/galaxy-101-ngs-variant

1. Picard tools  not recognized across revisions. No initial warning message upon import about these tools. 

2. FreeBayes and Variant Annotator not recognized.

3. While 'Merge BAM Files is present and appears to be non-problematics, it will not accept BAM input. You need to delete the imported version and add the tool fresh from the tool panel in order to make the connection.

4. Cannot save the workflow in the editor without removing them first (although a warning does exist for this. **It would be nicer if you could save mid-edit without needing to delete.**

These are the a graphics for warning messages and editor view of unrecognized tools that do exist on Test. 

![2015-01-23 am workflow import test 1](https://cloud.githubusercontent.com/assets/8999735/5879347/4a4f59a0-a2e3-11e4-9f1d-3427a14b2d07.png)

![2015-01-23 am workflow import test 2](https://cloud.githubusercontent.com/assets/8999735/5879348/5057071c-a2e3-11e4-9a66-f1c93414d970.png)

**Comment by jennaj** [comment]
Retesting - same issues with Picard tools. Including a successful job with a metadata setting error. Produced when executing SortSam one time (out of several).

**Comment by jennaj** [comment]
On Test, if a dataset is an input to a "grey - waiting to run job" - you cannot modify the metadata. Since the job hasn't started yet .. and will not until the metadata issue is cleared, I expected a "blue - paused job" instead. And to be able to fix the problem through auto-detect metadata correction.

Just leaving a note here in case pops up again. Could be due to prior issues. (Abondoning those datasets/jobs going forward in testing).

**Comment by jennaj** [comment]
'Collect Summary Metrics' is functioning on test now.

**Comment by jennaj** [comment]
"BWA for Illumina' fails if the read group settings do not use a fully capitalized "ILLUMINA". This seems tedious. Can we change it so that the info is case-insensitive?

Usage: bwa_wrapper.py [options]

bwa_wrapper.py: error: option --rgpl: invalid choice: 'Illumina' (choose from 'CAPILLARY', 'LS454', 'ILLUMINA', 'SOLID', 'HELICOS', 'PACBIO')

**Comment by jennaj** [comment]
Text cannot be copied from the updated tool forms. Can this be changed?

**Comment by jennaj** [comment]
Updating metadata with "auto-detect" for previously failed settings now functions (or did for one test case).

**Comment by nsoranzo** [comment]
> "BWA for Illumina' fails if the read group settings do not use a fully capitalized "ILLUMINA". This seems tedious. Can we change it so that the info is case-insensitive?
> 
> Usage: bwa_wrapper.py [options]
> 
> bwa_wrapper.py: error: option --rgpl: invalid choice: 'Illumina' (choose from 'CAPILLARY', 'LS454', 'ILLUMINA', 'SOLID', 'HELICOS', 'PACBIO')


@jennaj I think "BWA for Illumina" is deprecated in favor of BWA and BWA-MEM tools. Its only advantage is that it still accepts also fastqillumina files.

**Comment by martenson** [comment]
I tried to put a complete list in the first @jmchilton post and deleted multiple duplicates/resolved posts. This approach of having all the issues on Test tracked in one GH 'issue' is not working well for me so I discouraged @jennaj from using it and we go back to Trello.

The worflow import problems are expected as some tools changed their ids. :(

**Comment by peterjc** [comment]
Why not use one GitHub issue per problem? A single GtiHub issue with a list seems troublesome.

**Comment by martenson** [comment]
@peterjc You are right Peter. However another problem is that some of these are Galaxy-related and they belong to Trello. I would like to have only tool-related issues in this repo.

**Comment by nsoranzo** [comment]
I think this issue should be closed: as I mentioned above "BWA for Illumina" is deprecated in favor of BWA and BWA-MEM tools, and the remaining problems are Galaxy-related and not tool-related, as said by Martin.

**Comment by martenson** [comment]
closed, the galaxy-related stuff can be found at https://trello.com/b/75c1kASa/galaxy-development
