### ISSUE TITLE
BWA-MEM is not assigning read groups

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-devteam#88]
reported by @jennaj

**Comment by nsoranzo** [comment]
If you mean that the output BAM does not contain the header, this is due to https://github.com/galaxyproject/tools-devteam/blob/master/tools/bwa/bwa-mem.xml#L130 . To add the header ```s/samtools view -Sb/samtools view -Sbh/``` .

In the old "Map with BWA for Illumina" wrappers there was an option for this, "Suppress the header in the output SAM file", with "No" as default.

**Comment by martenson** [comment]
I think this is related and hopefully resolved by https://github.com/galaxyproject/tools-devteam/pull/89

**Comment by blankenberg** [comment]
I think you only need the -h if the input is a BAM, here the input is a SAM (-S)

**Comment by nsoranzo** [comment]
Sorry, you're right, the bugfix by John is correct.
